apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: devopsdaysworkshop
build:
  artifacts:
  - image: maxandersson/backend
    context: backend
    docker:
      dockerfile: Dockerfile
  - image: maxandersson/frontend
    context: frontend
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - kustomize/dev
profiles:
- name: base
  deploy:
    kustomize:
      paths:
      - kustomize/base
