apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base
- ./neo4j/templates

configMapGenerator:
- name: config
  env: .env.dev

patchesStrategicMerge:
- backend-deployment.yaml

