apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base
- ./neo4j/templates
- ./grafana/templates

resources:
- ./prometheus/main.yaml

configMapGenerator:
- name: config
  env: .env.dev.2

patchesStrategicMerge:
- backend-deployment.yaml

