---
# Source: neo4j/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-neo4j-secrets
  labels:
    app.kubernetes.io/name: neo4j
    helm.sh/chart: "neo4j-4.4.5"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "release-name"
type: Opaque
data:
  neo4j-password: "bXlTZWNyZXRQYXNzd29yZA=="
